#!/usr/bin/python3

import os

HOME = os.environ['HOME']
raw = list()
colors = list()

with open(f'{HOME}/.cache/wal/colors', 'r') as f:
    for line in f:
        raw.append(line.rstrip())

for i in range(8):
    colors.append((raw[i], raw[i + 8]))
