#!/bin/sh
# width=$((COLUMNS / 8))
width=$(($(tput cols) / 8))
for x in  0 1; do
    for i in 0 1 2 3 4 5 6 7; do
        printf "\e[48;5;$((i+x*8))m%${width}d\e[0m" $((i+x*8))
    done
    echo
done
