#!/bin/sh 

_inc() {
        local arg="${1%\%}"
        new="$(echo "scale=2; ${current} + ${arg} / 100 * ${max}" | bc)"
        new="${new%.*}"
}

_dec() {
        local arg="${1%\%}"
        new="$(echo "scale=2; ${current} - ${arg} / 100 * ${max}" | bc)"
        new="${new%.*}"
}

_write() {
        echo "${new}" > "${base}/brightness"
}

base='/sys/class/backlight/intel_backlight'
read -r current < "${base}/brightness"
read -r max < "${base}/max_brightness"

case "$1" in
        inc) _inc "$2" ;;
        dec) _dec "$2" ;;
esac

if [ ! -z "${new}" ]; then
        _write 
fi
